[package]
name = "angr-bad"
version = "0.1.0"
authors = ["Benjamin Levy <blevy@protonmail.com>"]
edition = "2018"

[dependencies]
capstone = "0.6.0"
goblin = "0.1.1"
petgraph = "0.4.13"
maplit = "1.0.2"
